### ISSUE TITLE
View channel's past streams

### ISSUE THREAD

**Issue by v1kn** [vinszent/gnome-twitch#112]
FIrst of all: great app!  
Are there any plans to be able to search streams that are offline, and to access past streams of a given channel? That would really liberate me from ever touching twitch website

**Comment by jangernert** [comment]
I guess that would be the "VODS" point on the todo-list ;)
https://github.com/Ippytraxx/gnome-twitch/blob/master/TODO.org#vods

**Comment by Ippytraxx** [comment]
Yep VODs and offline streams/channels are coming.

**Comment by v1kn** [comment]
Great, thanks for the info

**Comment by vinszent** [comment]
Fixe by #172
