### ISSUE TITLE
Tiny headerbar with eGTK-theme

### ISSUE THREAD

**Issue by jangernert** [vinszent/gnome-twitch#123]
With the elementary Gtk+ theme the headerbar is really thin. Adding the "titlebar" style class to either the browser- or the player-headerbar fixes this issue for me.

![screenshot from 2016-05-14 14-20-14](https://cloud.githubusercontent.com/assets/12012494/15268549/9d198570-19e3-11e6-99f5-58f8ae580b3b.png)

![screenshot from 2016-05-14 14-19-21](https://cloud.githubusercontent.com/assets/12012494/15268550/9e6579ac-19e3-11e6-8884-26479cc54b4b.png)

**Comment by Ippytraxx** [comment]
Hmm interesting, because the GtkStack that the headerbars are in has the titlebar CSS class. Guess it doesn't hurt to add it the actual headerbars themselves.

**Comment by jangernert** [comment]
I guess eGtk handles this differently than other themes. Btw: the same goes for the header-bar in the full-screen view. Only there the bar is completely transparent. Again adding "titlebar" fixes this.
