### ISSUE TITLE
Objects are not properly destructed

### ISSUE THREAD

**Issue by dchristidis** [vinszent/gnome-twitch#132]
I have been unable to identify the root of this issue, but here are two cases that display it:

1. When watching two streams and closing one of the windows, the audio can still be heard. Eventually, GNOME Twitch crashes.
2. Even when having a single window, the `finalize` function of `GtPlayerClutter` is never called.

**Comment by Ippytraxx** [comment]
Yeah, I've been a bit lazy with making sure everything is destructed nicely and just relied on people only using one window :P Probably a few loose references lying around, I'll see if I can clean them up.

**Comment by Ippytraxx** [comment]
Found the culprit at least for GtPlayer, the GPropertyActions all hold references. So they should be released first in the destroy signal as it's a cyclic reference and then they will release theirs in the finalize signal. I'll get this cleared up in the new player-backend system.
