### ISSUE TITLE
Cannot remove chatbar

### ISSUE THREAD

**Issue by Svendheim** [vinszent/gnome-twitch#150]
It says I'm logged in, but still not working, and I can't figure out how to remove the non functional sidebar
![bug](https://cloud.githubusercontent.com/assets/20624479/17443523/573d0740-5b3b-11e6-9666-b77b50779fcc.png)

**Comment by dengelt** [comment]
The login problem looks like this one: https://github.com/vinszent/gnome-twitch/issues/140

For hiding the chat side bar: Does the little speech bubble button in the header bar not work?

**Comment by Svendheim** [comment]
Haha! I didn't notice the speech bubble icon, since it was greyed out. Thank you for the help. Closing, since this is now a duplicate :) of #140
