### ISSUE TITLE
"develop"-branch currently broken

### ISSUE THREAD

**Issue by jangernert** [vinszent/gnome-twitch#151]
I know that this is probably still very work-in-progress, but I just want to give some feedback since it is easy to overlook these things as developer.
The branch is missing the "gt-log.h"-file that should have been added with this commit  4ffda2357d0ecf3181dceb239c21ab8a09a8c39c.
After getting it to build the program still segfaults because of

> Settings schema 'com.gnome-twitch.app' does not contain a key named 'loaded-plugins'

The schema file with the key is installed in /usr/share/glib-2.0/schemas/, I compiled the schemas manually a hundred times, but the "loaded-plugins"-key does simply not show up. No idea why.
When I introduce a syntax error in the file the schema compilation fails. But no matter what I change I make other than that, it won't show up in `gsettings list-keys com.gnome-twitch.app`. Changing every other schema and then compile the folder works perfectly.
Something weird is going on here.

**Comment by vinszent** [comment]
Woops, yep you're right gt-log.h should definitely be up on GH.

The schema problem sounds really weird indeed, can you possibly try ninja install? Sounds unlikely that it would make a difference but at least I know what steps are being performed then.

**Comment by jangernert** [comment]
Of course I tried the normal install with ninja-build first. The meson_post_install.sh was also run correctly.
You can probably ignore the gsettings-issue until someone else reports the same issue. Maybe something is broken on my machine :P

thx for adding the gt-log.h :)

**Comment by dengelt** [comment]
I think I had a similar issue way back when some other property was introduced. Can you check if you have an old schema in `/usr/local/share/glib-2.0/schemas/`? I think they get prioritized over the ones in `/usr/share/glib-2.0/schemas/`.

**Comment by jangernert** [comment]
Yes, there was a gnome-twitch schema in /usr/local/ at the beginning. But at some point I deleted it.
Just now I also deleted the gschemas.compiled-file and recompiled the schemas in /usr/local/ and recompiled all the schemas in /usr/ afterwards. Now it works. No idea if it was because of it, or just because I rebooted the PC in the meantime. :P
