### ISSUE TITLE
Favorites/Follows sync not working in v0.2.1

### ISSUE THREAD

**Issue by dengelt** [vinszent/gnome-twitch#152]
1. If there are local favorites from previous versions and I say "yes" to syncing them to Twitch, they are simply discarded (and not synced to Twitch) and the already existing Twitch follows are displayed.

2. If there are local favorites from previous versions and I say "no" to syncing them to Twitch, they are also discarded. I think this is currently intended but the message doesn't say that the local favorites are discarded if I press "no".

3. If I favorite a stream in the new version, it is neither synced to Twitch nor kept locally and is instead discarded when the application exits.

Furthermore, it would be nice if I could have local favorites and Twitch follows at the same time, e.g. by having two buttons on a channel: One for following and one for saving the channel to the local favorite list. The follow button could use the "heart" icon and would only be available if the user is logged in to Twitch and the button for saving locally could use a "save" icon. This would probably make tooltips for the 2 buttons necessary though.

**Comment by vinszent** [comment]
Actually your local favourites are backed up to 

    ~/.local/share/gnome-twitch/favourite-channels.json.bak

Also I'm pretty sure the source of your problem is that you need to refresh your login token so GT can get new permissions to edit your follows. I know I haven't made that clear at all :P.

As for your bottom paragraph, that was my original intention, but then I thought why? Why would a person want a channel favourited locally but not followed on Twitch. There are probably some scenarios but they are few.

**Comment by dengelt** [comment]
Refreshing the login token did indeed make the sync work, and now that you say so, I remember this already came up at some point in a discussion on some issue, although an error message would have been nice, if Twitch also provides one and doesn't just silently ignore the request ;).

For the proposed feature I can only really think of 3 unlikely use-cases right now. 

1. It would make migrating from one account to another easier (although there are not many legitimate reasons for doing so). 

2. You still have fast access to your favorite stream if you can, for some reason, not log into your account at the moment.

3. Someone wants to discontinue using his/her account altogether, but still watch streams without an account.

**Comment by vinszent** [comment]
Yes definitely, I'm currently working on showing errors to users on the develop branch, I just kinda fell behind the whole Client-ID thing and did this in a rush...

Maybe a migration tool might work, for at least 1 and 3? I find 2 to be very improbable as you only have to log in once (hopefully hehe) so if you can't log in that first time then you should still have your local favourites.

Btw thanks as always for providing your time for feedback!

**Comment by dengelt** [comment]
Yes, they are definitely unlikely scenarios and there are more important things to worry about. Just wanted to get it out while it was kinda "on topic".
