### ISSUE TITLE
Gnome-Twitch does not work with new twitch quality names

### ISSUE THREAD

**Issue by acz13** [vinszent/gnome-twitch#153]
the menu seems to be static on mobile-low-medium-high-source while some streams (for the International as an example) use 240p30, 360p30, 480p30, 540p30, 720p30 and 720p60 (+ source of course)

**Comment by vinszent** [comment]
Hmm this seems to only be for The International stream. I can support the extra qualities, but GT won't be able to store it in the settings as that requires them to be static (which they aren't).

**Comment by acz13** [comment]
This does not seem to be only the International stream... CapcomFighters does it too

**Comment by vinszent** [comment]
Fixed by e3ffa9304f591f2dc24d168d70e44a0d0b7b9cf8.
