### ISSUE TITLE
Sagfault in gt-channel.c:update_set_cb

### ISSUE THREAD

**Issue by Eijebong** [vinszent/gnome-twitch#155]
Hi, I have no idea why, but gnome-twitch (branch develop) segfaults on update_set_cb on this line.

`g_info("{GtChannel} Finished update '%s'", raw->name);`

When using gdb, it showed me that raw was NULL (0x0), si I just added a check to see if raw was not null or return above.
`if(!raw) return;`

Since then, I've got no segfault. I'm not sure if this is the good way to do it but maybe you can figure out why raw is NULL ^^

**Comment by vinszent** [comment]
Hmm a bit weird considering I actually do a NULL check in update_cb and update_set_cb is just called on the main thread after. I'll look into it.
