### ISSUE TITLE
The MPV opengl backend plays the first seconds of a stream twice

### ISSUE THREAD

**Issue by Eijebong** [vinszent/gnome-twitch#158]
When joining a stream, the first seconds are played twice (once, goes back and then a second time).

**Comment by vinszent** [comment]
Yeah I saw this two but it seems it is a bug in MPV that looks like to have appeared very recently for whatever reason. I can replicate it by just opening a stream link in MPV and it will also repeat the first second.

**Comment by Eijebong** [comment]
It seems to be fixed on archlinux, so I guess mpv has been fixed :)
