### ISSUE TITLE
Steam stuck on loading stream

### ISSUE THREAD

**Issue by gameslayer** [vinszent/gnome-twitch#160]
Hey all just wanted to report a bug with Gnome Twitch that another user and confirmed tested myself. if you try and load any stream it gets stuck on loading stream.

**Comment by vinszent** [comment]
Do you have a h264 decoder installed? Please install for Ubuntu (and variants) ubuntu-restricted-extras and for Fedora gstreamer1-libav from RPMFusion.

**Comment by gameslayer** [comment]
yep problem solved by doing sudo apt-get install ubuntu-restricted-extras 

you should inform them they need to install that as no one will no that.

**Comment by vinszent** [comment]
It's on the main page... Unfortunately  `ubuntu-restricted-extras` can't be put as a hard dependency on Ubuntu (I'm not the package maintainer there anyways).

**Comment by gameslayer** [comment]
It is fine to install if it needs it than it's fine to better mention that it needs it when installing it for Ubuntu based distros
