### ISSUE TITLE
Add emoji picker for chat

### ISSUE THREAD

**Issue by iommu** [vinszent/gnome-twitch#169]
Just a suggestion but I think it would be cool to add a quick pop up menu to the "Send a messge" text box for selecting emojis

**Comment by vinszent** [comment]
Hehe already one step ahead of you 735e6d743ca77a247841a63d507a0919ae68fcde. It will be available in the next release (v0.3.0) which should come out this weekend.

**Comment by iommu** [comment]
Haha that's great. Thanks for putting in so much effort to make this a polished application.
