### ISSUE TITLE
Translations for 0.3.1

### ISSUE THREAD

**Issue by vinszent** [vinszent/gnome-twitch#175]
@pfent @hmsintrepide @piotrdrag @Generator @kostich @Eljava @riflex @Generator @Sunderland93

I've prepared everything (I hope) for v0.3.0 which I will be releasing on Monday (29/09).

 Seeing as ninja no longer provides the pot target, I've added a template file `gnome-twitch.pot` to the `po` directory, which you can edit.

You can also easily run `msgmerge -U $LANG_CODE.po gnome-twitch.pot` to add the newer strings to your existing translation. Also please update any metadata so @dengelt doesn't have to do it :stuck_out_tongue:.

It's fine if you're not able to complete the translation by Monday (short notice by me), I'll just include it in the next release, v0.3.1, which I'll released in a week or two, along with fixes to bugs that have occurred.

Simply submit PR's with your translations and I'll merge them after a quick check. Thanks again for your support!

**Comment by dengelt** [comment]
@vinszent also don't forget to update the version in meson.build, it was still 0.2.0 in the 0.2.1 release :stuck_out_tongue_winking_eye:

**Comment by piotrdrag** [comment]
Have you thought about joining GNOME infrastructure? You would get dozens of regular translations for free. :)

**Comment by vinszent** [comment]
Hmm not really. It was a huge hassle for me to just get the wiki page so I can't say I'm super enticed on moving to gnome.org. Plus I would only mirror code to GNOME's git as GH is a much better place for collaboration, for devs at least.

Is there someone I can contact, so I can look into it?

**Comment by piotrdrag** [comment]
Here is some info: https://wiki.gnome.org/Git/NewRepository

But only mirroring to git.gnome.org is probably not worth the effort.

**Comment by piotrdrag** [comment]
BTW, Project-Id-Version is not used for anything, as far as I know.
