### ISSUE TITLE
Automatically hide the mouse cursor

### ISSUE THREAD

**Issue by dchristidis** [vinszent/gnome-twitch#183]
Congratulations on the new release. As a results of the changes in `GtPlayer`, the mouse cursor remains visible at all times. It would be nice to have it become invisible, like before. I tried to implement this myself, but I had issues with crossing events.

**Comment by vinszent** [comment]
Ok no probs, I'll see what I can do.

**Comment by vinszent** [comment]
Wait, what do you mean by crossing events? I'm pretty sure I've fixed it now, but there might be some scenario I'm not considering.

**Comment by dchristidis** [comment]
The cursor should not be hidden when it is not located over the player. I thought that would require handling `leave-notify-event`. Did you address this differently?

See commit 9fc3b55d95bb454799677725b0f821f59ee6b08a.

**Comment by vinszent** [comment]
@dchristidis Can you confirm that commit https://github.com/vinszent/gnome-twitch/commit/836a4ace6ea0f2b49e963ca0476bf945587bc090 fixed this?

**Comment by dchristidis** [comment]
Yes, it is fixed. I really like the implementation, thanks for looking into this.

There is just one corner case where it could be improved: enabling and disabling fullscreen mode using the keyboard shortcut. The cursor will remain visible or invisible respectively, until the mouse is moved.

**Comment by mecjuszfufecjusz** [comment]
I noticed that currently the cursor hides only in fullscreen mode. Is this intentional?

**Comment by vinszent** [comment]
@mecjuszfufecjusz Yes this is intentional.

**Comment by mecjuszfufecjusz** [comment]
I don’t really know if it is better, but other video players that I’m familiar with (VLC, HTML5 Youtube on Firefox) always hide the cursor when it’s over the video, regardless of being maximized or in fullscreen. Just wanted to point it out.

**Comment by dchristidis** [comment]
I would like to report another bug with the current implementation. The cursor hiding is performed even if it is not located over the player area. This affects the use of the audio volume slider and the hamburger menu. The cursor disappears when it leaves the popover area.
