### ISSUE TITLE
Error when trying to get Twitch follows

### ISSUE THREAD

**Issue by ptkato** [vinszent/gnome-twitch#195]
A message pops-up:

### Something went wrong
An error occurred when trying to get your Twitch follows
```
Twitch replied with error code '400', message 'Bad Request' and body '{"error":"Bad Request","status":400,"message":"No client id specified"}'
```

**Comment by chapel** [comment]
Looks like they finally pulled the trigger and made the client ids required. See here: https://blog.twitch.tv/client-id-required-for-kraken-api-calls-afbb8e95f843

Though along with that looks like Twitch API service is down as of this comment seen here: http://twitchstatus.com/

It looks like I'm not able to do anything now. Streams don't load, just spin saying they are loading. Chat obviously doesn't work at the moment.

**Comment by vinszent** [comment]
I'm sending the Client-ID, twice... Which the Twitch API can't handle apparently. I'll fix it ASAP.

**Comment by unixfox** [comment]
Can you create a new release @vinszent ? I can't have my followed streams on Gnome Twitch anymore.

**Comment by vinszent** [comment]
@unixfox Sorry for the delay. Thanks for reminding me ;)
