### ISSUE TITLE
[Wishlist] Add message about installing player backend if none is installed

### ISSUE THREAD

**Issue by dengelt** [vinszent/gnome-twitch#200]
Currently, when the user does not have a player backend installed and clicks the "Click here to load one" message, he just sees an empty plugin list. It would be nice if there would be a message like "There seems to be no player backend installed. Please install at least one.".

The reason is that I'm currently thinking about replacing the dependency from gnome-twitch on its player backends in my Debian package with a recommendation (to solve a circular dependency problem), which would mean that a user who has apt configured to not automatically install recommended packages could get confused, because he probably never read the README and doesn't know that he needs to install an additional package.

**Comment by vinszent** [comment]
Hmm yeah, to be honest, I've been thinking of dumping my intended plugin system. I realised now from what users are experiencing that it might be more hassle than what it's worth. Things always seem like a good idea for the first time ;).

I think I'll just turn the "backend choosing" into a compile flag as I doubt users will be switching them often. If they want to try another one, they can simply just install another package. The GStreamer-Cairo will be compiled in by default if no other one is chosen.

Does this also make things easier for you as a package maintainer?

**Comment by dengelt** [comment]
I'm not exactly sure what you mean by that.

> I think I'll just turn the "backend choosing" into a compile flag

Isn't that the status quo?

> If they want to try another one, they can simply just install another package. 

That's the current situation with my Debian package. I build all player backends and then split them into different binary packages, so that I have these packages:

```
gnome-twitch
gnome-twitch-player-backend-gstreamer-cairo
gnome-twitch-player-backend-gstreamer-clutter 
gnome-twitch-player-backend-gstreamer-opengl
gnome-twitch-player-backend-mpv-opengl
```

The user can then install as many backends as he wants (if he just installs `gnome-twitch`, the cairo backend will automatically be installed).


If you just kind of "merge them all into the main executable", the user would still have to choose one backend at run-time, with the downside that the main executable depends on all the dependencies of all backends.

If there can only be one backend chosen to be compiled into the main executable, the user would need to recompile/reinstall the whole app to switch the backend. Packaging this would require building the package 4 times with different flags, and then splitting these 4 builds into their own packages, which would probably get weird looks since the packages are almost identical. Also the packages would probably not be co-installable since they would all provide the same files (just with a different `usr/bin/gnome-twitch`).

**Comment by vinszent** [comment]
Ok I understand, so you're saying it's easier the way it already is? It makes no difference either way for me, just wanna do easiest :smile: 

Also I meant pretty much what you wrote in the last paragraph. You choose one backend at compile time and to change it you recompile the entire program. This requires, like you said, 4 different packages each doing the same thing, just with different backends.

**Comment by dengelt** [comment]
Yes, I can't currently think of an easier way than the status quo that keeps the current flexibility and modularity. The only potential problem I see arising with the plugin system is that when more types of plugins come (like a BTTV plugin), they get "mixed" with the player backends. 

Lets assume the user has not installed a player backend, but two other plugins. He opens a stream, clicks the link asking him to choose a backend and the plugin list opens, showing the two other plugins. 

I don't know how flexible libpeas is, but if it is possible to assign something like a tag or a label to a plugin, then this could however easily be solved by having an additional "Player Backends" tab in the settings dialog, which is opened instead of the Plugins tab when the user is prompted to choose a backend. The player backends would be sorted into the tab for the player backends, and the other plugins into the tab for the generic plugins.

**Comment by vinszent** [comment]
Awesome, sounds good to me. I'll see if I can figure out a solution to the sorting problem then.

Back to the original issue: I was thinking of opening a wiki page with instructions and links on how to install backends for different distros.

**Comment by dengelt** [comment]
Badly GIMPed example of how I think it could look like (with the addition of separate tabs for player backends and plugins, but my GIMP skills aren't high enough for that 😉):

![bildschirmfoto von 2016-10-01 05-43-17](https://cloud.githubusercontent.com/assets/15182482/19011603/daea11be-879b-11e6-9ccd-88e6cc4a9985.png)

The link at the bottom would lead to a wiki page like you described.
