### ISSUE TITLE
Green screen on Debian stretch

### ISSUE THREAD

**Issue by drdaffey** [vinszent/gnome-twitch#204]
I can't seem to get the video stream to work on Debian stretch. Audio works fine, video just stays green. Any ideas please?

**Comment by dengelt** [comment]
What player backend are you using?

**Comment by drdaffey** [comment]
GStreamer Cairo

**Comment by vinszent** [comment]
Do you have all the GStreamer dependencies from the readme installed?

**Comment by drdaffey** [comment]
I assumed the Debian packages would install all dependencies automatically. I'll try reinstalling and using different backends. Thanks for your help.

**Comment by vinszent** [comment]
@drdaffey Were you able to fix the issue? @dengelt maintains the Debian package but I know a lot of distros can't have the `gst-libav` package in their official repos due to licensing issues. I'm working on comprehensive install guide and having notifications in GT, so hopefully it won't be so confusing in the future :smile:

**Comment by dengelt** [comment]
It seems that I forgot to add the dependency to `gstreamer1.0-libav` (the Debian equivalent of `gst-libav`). But what I don't understand is this: Why are the `gst-plugins-base` and `gst-plugins-good` and `gst-plugins-bad` packages needed? All streams on Twitch should be encoded in h.264 if I remember correctly, and that codec is already covered by libav.

**Comment by vinszent** [comment]
`gst-plugins-bad` is needed for the HLS demuxer. `gst-plugins-base` and `gst-plugins-good` have a lot of standard components and AAC decoding for the audio.

**Comment by dengelt** [comment]
Ok thanks. I will update my package, but it will take a few days to reach the testing branch.

**Comment by drdaffey** [comment]
I'm sorry I've not commented on here. I've not been able to fix the issue at one point having all libav dependencies though it became such a mess I'd rather reinstall just the required dependencies. Other GTK3 applications which play video have the same issue, e.g. Corebird for Twitter.

**Comment by drdaffey** [comment]
As a follow-up (I understand it's been a long while), today I had issues getting gnome-twitch to work from Debian's unstable repository. I got a black screen with all libraries installed.
Installing the gnome-twitch_0.4.1-1 and gnome-twitch-player-backend-gstreamer-cairo_0.4.1-1 packages from Debian's Experimental worked like a charm.
