### ISSUE TITLE
Make chat input box unfocusable by clicking on stream video

### ISSUE THREAD

**Issue by mecjuszfufecjusz** [vinszent/gnome-twitch#206]
As it seems, currently you can unfocus chat input box only by clicking on one of buttons on the top panel. It wouldn’t be a big deal, if this didn’t prohibit you from using shortcut for fullscreen mode, i.e. ‘f’ (you may end up with several ‘f’s written in the input box before you notice why the shortcut doesn’t work). Maybe user could reset focus by simply clicking on stream video (if not anywhere else than chat panel)?

**Comment by dengelt** [comment]
You can also unfocus chat by pressing `tab`. Works for me at least. But unfocusing chat after the user clicks on the stream seems like a good idea too.

**Comment by vinszent** [comment]
Yeah seems like natural behaviour, I'll slate this for the next release.

**Comment by mecjuszfufecjusz** [comment]
Another thing (if I could add this here) – today I noticed that clicking on chat widget (not the input box) also prohibits gnome-twitch from handling `f` shortcut. In this case `f` seems to either do nothing or to scroll to some random (as it seems to me) point of the conversation.

Yet another thing – it appears that you can also press `Ctrl + F` and `Alt + F` to toggle fullscreen, this time regardless of the focus. Is this, well, _abundance_ of shortcuts intentional?

**Comment by vinszent** [comment]
Yeah shortcuts are done kind of sloppily right now. For 0.4.0 I'll be implementing proper handling of shortucts as well as use the new GtkShortcutsWindow. Thanks for pointing these out.
