### ISSUE TITLE
Segmentation fault when watching streams

### ISSUE THREAD

**Issue by balroggg** [vinszent/gnome-twitch#209]
Some random crash programm when watching streams with no chat
I used GT 0.3.0 and GT r740.cf555c7 think have same issue. My distro ArchLinux  4.8.7-1-ARCH.

Gdb shows me:
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Core was generated by `gnome-twitch -l debug'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fd139ce5032 in ?? () from /usr/lib/gstreamer-1.0/libgsthls.so
[Current thread is 1 (Thread 0x7fd127dff700 (LWP 17854))]
(gdb) bt
#0  0x00007fd139ce5032 in  () at /usr/lib/gstreamer-1.0/libgsthls.so
#1  0x00007fd139ad7d0a in  () at /usr/lib/libgstadaptivedemux-1.0.so.0
#2  0x00007fd15695ea81 in  () at /usr/lib/libgstreamer-1.0.so.0
#3  0x00007fd161a6cace in  () at /usr/lib/libglib-2.0.so.0
#4  0x00007fd161a6c0d5 in  () at /usr/lib/libglib-2.0.so.0
#5  0x00007fd15e297454 in start_thread () at /usr/lib/libpthread.so.0
#6  0x00007fd15dfda7df in clone () at /usr/lib/libc.so.6
(gdb) Quit

**Comment by balroggg** [comment]
I have coredump, but I can not attach it, as it weighs 50MB (

**Comment by vinszent** [comment]
Hmm I've been getting this issue as well and from what I can see it originates from GStreamer code, so not much I can do unfortunately. I'm going to see if can get GST symbols installed so I can report this issue to them. If you want, you can always try the MPV backend (available in the AUR).

**Comment by balroggg** [comment]
Ok, thanks i try MPV.
