### ISSUE TITLE
Broken backends on Fedora 25

### ISSUE THREAD

**Issue by dchristidis** [vinszent/gnome-twitch#211]
I'm not sure what changed between releases, but two of the backends do not work as intended. Specifically, with `gstreamer-cairo` the stream appears in a separate window and with `gstreamer-opengl` there is no video at all, only audio.

`gstreamer-clutter` and `mpv-opengl` work fine.

**Comment by dchristidis** [comment]
After some additional usage, it turned out that `gstreamer-clutter` has an issue with the buffering spinner. The rectangle around it isn't transparent.

**Comment by vinszent** [comment]
Is this on Wayland?

**Comment by dchristidis** [comment]
No, these issues appear on an X11 session.

**Comment by vinszent** [comment]
Seems pretty wierd that something this drastic would change without GT changing. Are all the same GStreamer components installed? Black screen, etc is usually a sign of something component missing.

**Comment by dchristidis** [comment]
"Black screen" is not an accurate description. The player area is not black. Instead, it has the colour of the chrome. It looks like the stream is not embedded correctly in the window.

I repeated the installation in a virtual machine and got the same result. So, it should be possible to replicate these issues.

**Comment by vinszent** [comment]
Ok I'll see if I can replicate it then.

**Comment by sugatov** [comment]
Confirm. Had the same also on Fedora 24.

**Comment by vinszent** [comment]
Ok found the issue and it works now on my Fedora 25 install. The gtksink elements have been split off into their own package on Fedora due to https://bugzilla.redhat.com/show_bug.cgi?id=1295444. So you'll need to install `gstreamer1-plugins-bad-free-gtk` to get them. Make sure you also have all the usual `gstreamer1-libav` and `gstreamer1-plugins-[bad/good/base]-free` installed.

**Comment by dchristidis** [comment]
Thank you for providing a solution. This issue may now be closed, unless you wish to update `README.md`.
