### ISSUE TITLE
Neither Channels nor Games can be found / Screen stays blanc

### ISSUE THREAD

**Issue by Chieftecteufel** [vinszent/gnome-twitch#214]
Today I installed gnome-twitch on Ubuntu 16.04.1 LTS 64-bit.
Every time I open the application I am not able to see any channels, games or favourites(when I am logged in).
Even searching known channels does not solve the problem.

![screenshot from 2016-11-29 14-35-31](https://cloud.githubusercontent.com/assets/24249660/20712294/bddbceba-b643-11e6-8586-ec489d5d29d0.png)
 
 
![screenshot from 2016-11-29 14-44-46](https://cloud.githubusercontent.com/assets/24249660/20712305/c475b6be-b643-11e6-8e5f-02f9d37c7647.png)
Even after 15 minutes it kept searching. 
 
 
![screenshot from 2016-11-29 14-56-17](https://cloud.githubusercontent.com/assets/24249660/20712366/03178df2-b644-11e6-8946-15624846e51c.png)

**Comment by dengelt** [comment]
What version of `gnome-twitch` do you have installed? If my information is correct, the official repos of Ubuntu 16.04 only have version 0.1.0, which doesn't work anymore due to changes in the Twitch API. So if this is the case you'll have to get it from somewhere else or compile it yourself.

**Comment by vinszent** [comment]
Yeah, you'll need at least version 0.3.1.

**Comment by hunter-87** [comment]
all ppa linked in the main page provide at best 0.2.1 (webupd8 has 0.3 for ubuntu 16.10 but not for 16.04)
so  right now the only option is compile yourself

**Comment by TingPing** [comment]
@hunter-87 Could install the Flatpak: https://github.com/vinszent/gnome-twitch/wiki/How-to-install-FlatPak-package
