### ISSUE TITLE
No Fedora 25 builds in the COPR repo

### ISSUE THREAD

**Issue by blueish4** [vinszent/gnome-twitch#223]
The COPR repo linked in `README.md` has been configured to build for Fedora 23, 24 and the latest development version (now 26). Fedora 25 should be added to the build list. 

https://copr.fedorainfracloud.org/coprs/ippytraxx/gnome-twitch/

**Comment by TingPing** [comment]
Can always use the Flatpak ;)

**Comment by robotmaxtron** [comment]
@vinszent I'll take it on as a task to own the Fedora packaging for it.

**Comment by TingPing** [comment]
I commented on it here #233 but a few months ago the build system would run because they didn't use UTF-8 on their builders.

**Comment by dengelt** [comment]
Does Fedora support the C.UTF-8 locale? I had the same issue with my Debian builds, and setting `export LC_ALL=C.UTF-8` in the build script solved it. AFAIK, not all distributions have C.UTF-8 though.

**Comment by robotmaxtron** [comment]
@dengelt Based on https://bugzilla.redhat.com/show_bug.cgi?id=902094 it appears like it.

**Comment by TingPing** [comment]
Ok it built this time: https://copr.fedorainfracloud.org/coprs/tingping/gnome-twitch/

**Comment by robotmaxtron** [comment]
@TingPing I got some errors when trying to install on a pretty fresh F26 install.

```
sudo dnf install gnome-twitch
Copr repo for gnome-twitch owned by tingping     14 kB/s | 3.2 kB     00:00    
Last metadata expiration check: 0:00:00 ago on Sun 16 Jul 2017 11:15:30 AM CDT.
Error: 
 Problem: conflicting requests
  - package gnome-twitch-0.4.1-1.fc26.x86_64 requires gstreamer1(element-gtkglsink), but none of the providers can be installed
  - problem with installed package gstreamer1-plugins-bad-1:1.12.1-2.fc26.x86_64
  - installed package gstreamer1-plugins-bad-1:1.12.1-2.fc26.x86_64 obsoletes gstreamer1-plugins-bad-free-gtk < 1:1.12.1-2.fc26 provided by gstreamer1-plugins-bad-free-gtk-1.12.1-1.fc26.i686
  - package gstreamer1-plugins-bad-1:1.12.1-1.fc26.x86_64 obsoletes gstreamer1-plugins-bad-free-gtk < 1:1.12.1-1.fc26 provided by gstreamer1-plugins-bad-free-gtk-1.12.1-1.fc26.i686
  - package gstreamer1-plugins-bad-1:1.12.1-2.fc26.x86_64 obsoletes gstreamer1-plugins-bad-free-gtk < 1:1.12.1-2.fc26 provided by gstreamer1-plugins-bad-free-gtk-1.12.1-1.fc26.i686
```
I've got gstreamer1-libav-1:1.12.1-1.fc26.x86_64 already installed as well.

**Comment by TingPing** [comment]
@robotmaxtron Well that sounds like breakage on the end of those packages but I'm using RPMFusion on F26 and it resolves the dependencies just fine.

**Comment by TingPing** [comment]
Pushed a fix for it trying to install 32bit lilbs though... (not sure why it does that).

**Comment by robotmaxtron** [comment]
@TingPing the new build (https://copr.fedorainfracloud.org/coprs/tingping/gnome-twitch/build/580104/) works great. Thanks!
