### ISSUE TITLE
Cannot view channel until its thumbnail is loaded

### ISSUE THREAD

**Issue by mecjuszfufecjusz** [vinszent/gnome-twitch#225]
Currently you have to wait until GNOME Twitch loads specific channel’s thumbnail until you can view this channel, which can be a bit annoying if you are, let’s say, watching some majors, your stream gets stuck and you have to reload (currently by going back and clicking on desired stream again). Maybe this behaviour could be changed?

**Comment by vinszent** [comment]
No problem, this can done. Can I just ask, what problems with the stream are you encountering?

**Comment by mecjuszfufecjusz** [comment]
You mean why do I have to reload? Sometimes streams just stop buffering and lock at 0%, reloading helps.

**Comment by vinszent** [comment]
I believe this is fixed now.
