### ISSUE TITLE
no feedback when game category is empty

### ISSUE THREAD

**Issue by andreasn** [vinszent/gnome-twitch#227]
I went to a game category (Dungeons and Dragons) that seems empty.

![screenshot from 2017-02-16 23-50-17](https://cloud.githubusercontent.com/assets/209895/23044958/dff14f0a-f4a2-11e6-8715-189d047d9d44.png)

I think it is empty at least. Or did  an error occur?

Maybe it should show a little message, similar to the "No channel followed" if you don't have anything in Follows. Something along the line of "There are currently no broadcasts for this game, please check back later" or something like that.

**Comment by vinszent** [comment]
Yes it's empty.  I've been implementing a lot of the GNOME UI functionality on the dev branch for next release. 

This is currently how the Dungeons and Dragons game looks: ![](http://i.imgur.com/HLQSQU1.png)

This is similar to #218 which has also been greatly improved, so users should in most cases get some kind of visual error.

Still, thanks for your feedback!

**Comment by andreasn** [comment]
I guess that makes this issue resolved then. Closing.
