### ISSUE TITLE
Notifications of who you follow going live

### ISSUE THREAD

**Issue by LiamDawe** [vinszent/gnome-twitch#234]
One thing I would like to see, is to have desktop notifications for when streamers you follow go live.

Simple, but very useful.

**Comment by vinszent** [comment]
Yes definitely! GT used to have them, but they were a bit buggy so I disabled them for a release. I'll be re-enabling them this release.

**Comment by LiamDawe** [comment]
Fantastic news, will make the application even more useful!

**Comment by ptkato** [comment]
Did those work even with GT closed?

**Comment by TingPing** [comment]
@ptkato It could run in the background without a window.
