### ISSUE TITLE
Channels never load if selecting follows before thumbnails load

### ISSUE THREAD

**Issue by ptkato** [vinszent/gnome-twitch#238]
It's kinda odd, but when I open GT and quickly select "Follows", before the thumbnails in "Channels" are loaded, they simply don't load, nor do the followed channels.

**Comment by vinszent** [comment]
Is this happening on master? I have a few changes to push regarding follows so I'll need you to check again once they are up on GitHub.

**Comment by ptkato** [comment]
Yeah @vinszent , it's gone now.

**Comment by vinszent** [comment]
Ok great!
