### ISSUE TITLE
Crash when loading chat badges

### ISSUE THREAD

**Issue by speace** [vinszent/gnome-twitch#240]
Hi, I have a weird crash my desktop on which I installed GT for the first time recently but not on my old laptop install.  
I installed the archlinux git package with Gstreamer backend.  
It happens on all streams I  tried so far and the error message is the following and I can give you the core dumped if needed.

> [16:44:37] Warning - GNOME-Twitch : {GtTwitch:1386} Error downloading picture for url 'https://static-cdn.jtvnw.net/badges/v1/a9811799-dce3-475f-8feb-3745ad12b7ea/1' because: Format d'image non reconnu
[16:44:37] Warning - GNOME-Twitch : {GtTwitch:1529} Unable to fetch chat badge set with name 'global' because: Unable to download picture for url 'https://static-cdn.jtvnw.net/badges/v1/a9811799-dce3-475f-8feb-3745ad12b7ea/1' because: Format d'image non reconnu
[16:44:37] Critical - GLib-GObject : g_object_unref: assertion 'G_IS_OBJECT (object)' failed
[16:44:37] Warning - GNOME-Twitch : {GtTwitch:1588} Unable to load chat badge sets for channel '71852806'
**
ERROR:../src/gt-irc.c:1060:gt_irc_connect_and_join_channel: assertion failed (err == NULL): Unable to load chat badge sets for channel '71852806' because: Unable to fetch chat badge set with name 'global' because: Unable to download picture for url 'https://static-cdn.jtvnw.net/badges/v1/a9811799-dce3-475f-8feb-3745ad12b7ea/1' because: Format d'image non reconnu (gdk-pixbuf-error-quark, 3)
[1]    850 abort (core dumped)  gnome-twitch

**Comment by vinszent** [comment]
Yeah I also got this problem but I believe I've already fixed this 1a276b7. The problem is that the picture its trying to download is corrupted (you can try clicking on the link). Can you update the package an verify if the problem still persists?

**Comment by speace** [comment]
I'm already using the latest version of the git package according to yaourt (pacman with AUR capabilities).

**Comment by vinszent** [comment]
What version does GT say it is? You can run `gnome-twitch --version` or go to `App menu -> About`.

**Comment by speace** [comment]
r938.4fbbb62 on desktop (where the crash happens)  
0.3.0 on laptop (not the git package and working)

**Comment by vinszent** [comment]
Ok r938 is quite old (for the git version 😄 ). Latest git version is r997 which should have the fix for this problem.

**Comment by speace** [comment]
Ok thanks, I didn't know about yaourt and git packages.

**Comment by vinszent** [comment]
No problem, happy to help.

**Comment by speace** [comment]
Just a message to confirm updating to r997 fixed it.
