### ISSUE TITLE
followed-channels.json not saved.

### ISSUE THREAD

**Issue by Techwolf** [vinszent/gnome-twitch#252]
From the console output:
```
[16:52:53] Message - GNOME-Twitch : {GtFollowsManager:696} Saving follows fo file '/home/techwolf/.local/share/gnome-twitch/followed-channels.json'
```

After closing the program:

```
$ ls -la /home/techwolf/.local/share/gnome-twitch/followed-channels.json
ls: cannot access '/home/techwolf/.local/share/gnome-twitch/followed-channels.json': No such file or directory

```

Also just notice a typo: fo should be to

**Comment by vinszent** [comment]
Have you followed any channels? The message is a bit missleading I guess but it won't actually save the file if there aren't any followed channes for it to save.

**Comment by Techwolf** [comment]
I follow *checks* !@#$#$#!@ twtich change things so one can NOT see that anymore. I do know I follow at least four channels.

**Comment by vinszent** [comment]
Yes but `followed-channels.json` is only for "local" follows i.e. when you're **not** logged into Twitch.

**Comment by Techwolf** [comment]
I am still a bit new to twitch. Did not know about local follows. Perhaps a better notice message?

**Comment by vinszent** [comment]
Local follows is unique to GNOME Twitch. My intention is to try and offer as much functionality to users that don't have Twitch accounts as possible and also to make this as seamless as possible (users don't need to worry if they're logged in or not, they will still be able to "follow" channels).

**Comment by vinszent** [comment]
If there isn't any other problems I'll close this issue as it seems to be resolved.
