### ISSUE TITLE
Suggestion: Remove minimum window size

### ISSUE THREAD

**Issue by seanbutnotheard** [vinszent/gnome-twitch#255]
Gnome-Twitch is really nice to use in general but it poses a bit of a problem for those (like myself) using tiling window managers due to the minimum window size. The window manager is able to place the window into position just fine, but since there is a minimum size (in particular the width), it ends up overlapping and obscuring other windows and generally getting in the way. I'd love to see this removed or at least reduced so the window could be (almost) any size.

**Comment by vinszent** [comment]
Sure, I actually think it's the title label in the player that is actually forcing a minimum size as I don't specifically enforce a minimum size on the actual window, but should be fixable.

**Comment by vinszent** [comment]
@seanbutnotheard This should be fixed now. There is still small inherent minimum width as the header bar has buttons that it can't ellipsize or make smaller. But you should be able to make it small enough now.
