### ISSUE TITLE
Fedora 25: {GtPlayer:1290} Can't open channel, no backend loaded

### ISSUE THREAD

**Issue by Blasterdick** [vinszent/gnome-twitch#264]
None of the backends avalilable, installing from source. Every dependency's resolved.

**Comment by dengelt** [comment]
How did you build the backends and where did you install them?

**Comment by Blasterdick** [comment]
@dengelt 

```git clone ..
cd gnome-twitch
meson build -Dbuild-player-backends=${player-backend-mpv-opengl}
sudo ninja-build -C build install```

**Comment by dengelt** [comment]
The third line should be `meson build -Dbuild-player-backends=mpv-opengl`

@vinszent Maybe there should be an example in the readme.

**Comment by vinszent** [comment]
Yeah sure, I can see how that can be confusing. I'll add an example like you said.
