### ISSUE TITLE
Translations for 0.4.1

### ISSUE THREAD

**Issue by vinszent** [vinszent/gnome-twitch#266]
@pfent @hmsintrepide @piotrdrag @Generator @kostich @riflex @Generator @Sunderland93 @CyberStar1 @kordianbruck @radek-sprta

Time for another release with new translations! Hopefully it shouldn't be too much but to make things easier I've setup a Zanata project [here](https://translate.zanata.org/project/view/gnome-twitch/master) and imported all existing translations (including the Spanish one @Eljava and @AlejandroC90). I encourage that you use Zanata, either via the web editor or command line, but you can still send me pull requests and I'll handle it. There's a short startup guide for Zanata [here](http://docs.zanata.org/en/release/user-guide/translator-guide/) if you haven't used it before. If there are any problems, just let me know.

**Comment by kostich** [comment]
I'm not able to translate on Zanata. The Serbian language is read-only for me. My username on Zanata is kostic.

**Comment by vinszent** [comment]
@kostich Ok thanks for notifying me, I've added you! Seems like I need to add translators to the project, so anybody that is planning on using Zanata just comment with your username and language, and I'll add you. I think there should be something like a "join project team" somewhere though...?

**Comment by AlejandroC90** [comment]
Add alejandroc90 to the Spanish translation

**Comment by vinszent** [comment]
@AlejandroC90 Done!

**Comment by CyberStar1** [comment]
cyber_star for the dutch translation! :)

**Comment by vinszent** [comment]
@CyberStar1 Done as well!

**Comment by Generator** [comment]
Portuguese translation updated

**Comment by vinszent** [comment]
@Generator Awesome, thanks a lot!

**Comment by pfent** [comment]
`pfent` for the german :de: translation

**Comment by Sunderland93** [comment]
sunderland93 for the russian translation

**Comment by vinszent** [comment]
@pfent @Sunderland93 Done and done, much appreciated!

**Comment by Sunderland93** [comment]
Russian translation updated

**Comment by kostich** [comment]
`
%s started streaming %s

#88; Refs: src/gt-follows-manager.c:85`

What is the context of this string? I guess it's $PLAYER started streaming $GAME. Can you add a comment to it describing the context? :)

**Comment by vinszent** [comment]
@kostich Ah sorry, but yes you are correct. The first `%s` is the steamer's username and the second `%s` is the game. I'll add a comment like you said.

**Comment by kostich** [comment]
@vinszent, excellent. Context helps us a lot.

Serbian is 100% finished.

**Comment by pfent** [comment]
German translation should be finished. Keep up your great work @vinszent !

**Comment by vinszent** [comment]
@kostich @pfent Thanks for your help!

**Comment by CyberStar1** [comment]
Dutch translation is finished! @vinszent

**Comment by vinszent** [comment]
@CyberStar1 Awesome! Thanks for your help as well 😄

**Comment by adrianjav** [comment]
Hi! These days I'm quite busy and I haven't kept tracked of this project. Despite of that I'm fine checking Alejandro's translation if need it.
Maybe we should try to make a neutral Spanish translation or split it up into Latin and Spain Spanish. I'm from Spain so I could do that part.

**Comment by radek-sprta** [comment]
rsprta@czech :]

**Comment by vinszent** [comment]
@radek-sprta I've added you now!

**Comment by riflex** [comment]
@vinszent I'm sorry, but can't finish up the Hungarian translation until next Wednesday, finals are coming :(

**Comment by vinszent** [comment]
@riflex No problem, take your time and just send a PR when you're ready.

**Comment by vinszent** [comment]
Thanks a lot guys for your hard work! Hopefully it was a lot easier to use Zanata and it should make future translation efforts a breeze.

@riflex @radek-sprta I'll merge in your translations when you're ready and create a new minor release, so no need to stress 😄 .

**Comment by radek-sprta** [comment]
Sorry, I was a bit busy lately. Finished now!

**Comment by vinszent** [comment]
@radek-sprta No problem, thanks for your contribution!
