### ISSUE TITLE
Thumbnails never load

### ISSUE THREAD

**Issue by ptkato** [vinszent/gnome-twitch#270]
The tumbnails never load:

![image](https://cloud.githubusercontent.com/assets/10677806/25571577/7e7245d8-2e07-11e7-922f-d9331252a2b0.png)

The same happens in the followed tab, with the exception of some loading only the default offline thumbnail.

Sometimes only a few load fine:

![image](https://cloud.githubusercontent.com/assets/10677806/25571534/0f447532-2e07-11e7-8a3b-a1ca077566f8.png)

Don't mind the weird colours, for some reason it does that to the window only screenshots.

**Comment by vinszent** [comment]
If there are no errors being shown, then it's probably a problem upstream like your internet connection or with Twitch itself. Could be that the Twitch servers in your area are under high load and therefore not serving up the images fast enough.

I'll be adding a timeout for 0.5.0 so they don't load indefinitely and will show you a timeout error or something.

**Comment by ptkato** [comment]
`then it's probably a problem upstream like your internet connection or with Twitch itself. Could be that the Twitch servers in your area are under high load and therefore not serving up the images fast enough.`

That's odd, because the streams play fine.

**Comment by vinszent** [comment]
The Twitch website and their streams are run from different servers so just because the stream plays fine doesn't mean the API will load fast. 

However I do see this occurr on some rare occassions myself, but generally if I then go onto the website, it also loads really slowly or not at all.

**Comment by ptkato** [comment]
I can see that, the thing is, it's happening for a few days now.

**Comment by vinszent** [comment]
No, the "lag" in #260 was because I was doing lengthy operations on the UI thread i.e. it would lag then. 
You can try running it from the command line and see if anything interesting is printed out, but I doubt it.
Also when it doesn't load, try loading the Twitch website itself and see if it's also slow.

**Comment by ptkato** [comment]
Twitch website loads fine. I asked about #260 because it started to happen more or less after 44cfb7d.

When a few load, they load almost instantly. And no, I took a look at the debug outbut and nothing interesting seems to be there.

**Comment by vinszent** [comment]
Hmm, I'll try see if I can find something but it's pretty hard as there are no errors and I can't really replicate it.

**Comment by vinszent** [comment]
@ptkato Actually I think I might've found the problem. Does this mainly happen when GT has been running for a while? Like more than 30 minutes?

**Comment by ptkato** [comment]
@vinszent, no it happens all the time, even if I just opened it, but who knows, the cause can be what you've found.

**Comment by Hund** [comment]
I have the same issue.

**Comment by vinszent** [comment]
It's due to the priority of followed channels, basically GT will load them first before other channels. However this leads to a bug when you have a lot of follows and it is constantly loading followed channels because they auto update.

Suffice to say I only discovered this recently (because I don't follow a lot of channels) but I'm working on a fix.

**Comment by Hund** [comment]
I see, thanks. :) I know this is OT, but is it possible to add an option to completely hide offline channels? I'm really confused about which is online or not. The only things that's differentiating them is a tiny title.

**Comment by vinszent** [comment]
Ah thanks for pointing that out. Seems like some of the GTK3 CSS styling rules have changed, the labels for offline channels should be a lot dimmer than online channels. I'll update the CSS rules.

**Comment by mecjuszfufecjusz** [comment]
I noticed today that this infinite thumbnail loading leads to massive CPU usage, which results in strange behaviour, e.g. when I watch a 1080p60 stream and turn on chat, the resized video stutters. When thumbnails happen to load (which seems to either happen within few seconds from running GT or never), there is no such issue. Cairo backend, don’t know about others.

**Comment by xKeiro** [comment]
I'm having the same issue as well (running gnome-twitch from Solus), as I can see this is quite an old problem, can we expect this issue to be solved any time soon, or is there a workaround?

**Comment by vinszent** [comment]
So this problem pretty much required a massive rewrite, which is done on the dev branch. However I'm working on a few more things that I want done before I release. 

Currently there is no easy work around, but the problem stems from having a lot of follows, so if you would logout (need to go into gsettings) then it should work again.
