### ISSUE TITLE
Change volumen by scrolling

### ISSUE THREAD

**Issue by sagcan** [vinszent/gnome-twitch#281]
I'd like to suggest implementing the feature to scroll at the volume icon to change value of it. As an example, Rhythmbox supports this feature.

**Comment by Eijebong** [comment]
Gnome twitch already does that I think

**Comment by TingPing** [comment]
It is a built-in feature of GtkVolumeButton actually so yes it already works.

**Comment by sagcan** [comment]
Oh shit, you guys are right. Last time I checked (on my Laptop) it didn't work but it does perfectly on my desktop. Might be something wrong with my touchpad then.   

Anyways, I'll close the Issue. Thanks!
