### ISSUE TITLE
Can't Build on Fedora

### ISSUE THREAD

**Issue by Aeirex** [vinszent/gnome-twitch#282]
Meson encountered an error in file meson.build, line 58, column 0:
Native dependency 'libpeas-1.0' not found

Package libpeas-1.20.0-3.fc25.x86_64 is already installed, skipping.

**Comment by TingPing** [comment]
`libpeas-devel` is the package you want.

**Comment by Aeirex** [comment]
@TingPing Thanks, it built fine.
