### ISSUE TITLE
RPM Package

### ISSUE THREAD

**Issue by Aeirex** [vinszent/gnome-twitch#283]
Instead of using RPMFusion, you can just use alien to convert a .deb package to .rpm and provide it as a download.  Using different Fedora builds is not really needed, you can just provide a generic RPM package after converting it from .deb.

I can provide the RPM packages for each release if you want me to.

**Comment by TingPing** [comment]
That is a terrible solution, converting between formats doesn't rebuild anything (so its entirely broken in concept) and loses useful information like dependencies.

If people need a generic package they have Flatpak, otherwise you simply need distro specific solutions.

**Comment by Aeirex** [comment]
@TingPing That's true, but I had to use it for SmartGit and worked fine.

**Comment by TingPing** [comment]
That is the problem with undefined behavior, it sometimes works. Every dependency has to exist and have the *exact same ABI* to work.
