### ISSUE TITLE
Follows not loading

### ISSUE THREAD

**Issue by derpyderpaderp** [vinszent/gnome-twitch#286]
I am having an error that prevents me from seeing my followers 
![22a7be16f7fcec7f5e8282470a4389ab](https://cloud.githubusercontent.com/assets/12119604/26773015/b051147e-498e-11e7-9913-bbb3c8baa221.png)
When I go to the followers tab it just sits at fetching channels and does nothing. It did this before but corrected itself but it stays that way now. Any help would be appreciated!

**Comment by vinszent** [comment]
Is this related to #276 ?

**Comment by derpyderpaderp** [comment]
Yes. Same error.

**Comment by derpyderpaderp** [comment]
Going to close it as It has already been detected as a bug.
