### ISSUE TITLE
Streams freezing

### ISSUE THREAD

**Issue by ptkato** [vinszent/gnome-twitch#290]
I'm watching fine, suddenly it freezes and I need to refresh, ok, the problem is that it's happening all the time. I tried to test with GStreamer Cairo and GStreamer OpenGL, both are affected. The chat stills fine, the only problem is the stream itself. I've been through all the quality options and no difference.

No output in debug too.

**Comment by vinszent** [comment]
I recently started encountering this too and it has to be a problem in GStreamer. It might be this issue https://bugzilla.gnome.org/show_bug.cgi?id=783314 which was introduced recently.

**Comment by ptkato** [comment]
Well, so I'll be using mpv as a workaround, then.

**Comment by vinszent** [comment]
Pretty sure this has been fixed now in `1.12.2` as I'm no longer seeing the freezes. Can you possibly confirm?

**Comment by ptkato** [comment]
Can confirm. This is no longer a problem.
