### ISSUE TITLE
Problem Building on Ubuntu

### ISSUE THREAD

**Issue by GalGR** [vinszent/gnome-twitch#296]
I know there's a similar thread on building in Fedora, but I'm still struggling to build.
Edit: gnome-twitch version 0.4.1
Here's the error:

Meson encountered an error in file meson.build, line 58, column 0:
Native dependency 'libpeas-1.0-0' not found

I have these libraries installed:

gir1.2-peas-1.0/zesty,now 1.20.0-1 amd64 [installed]
  Application plugin library (introspection files)

libpeas-1.0-0/zesty,now 1.20.0-1 amd64 [installed]
  Application plugin library

libpeas-1.0-python2loader/zesty,now 1.20.0-1 amd64 [installed]
  Application plugin library (Python 2 support)

libpeas-common/zesty,zesty,now 1.20.0-1 all [installed]
  Application plugin library (common files)

libpeas-dev/zesty,now 1.20.0-1 amd64 [installed]
  Application plugin library (development files)

**Comment by dengelt** [comment]
> Native dependency 'libpeas-1.0-0' not found

I think the dependency name should be 'libpeas-1.0'. What commit id do you build from exactly? What does your meson.build file contain at line 58?

In principle, `libpeas-dev` should be the right package for that dependency. Please run `pkg-config --print-provides libpeas-1.0` to check if pkg-config can find the dependency.

**Comment by GalGR** [comment]
sorry it took me so long to respond, but here it is:
I used apt-get build-dep + latest commit and it builds fine now!
I'm sorry if I wasted your time, keep up the good work!

**Comment by vinszent** [comment]
No problem, good to hear it's building now 😄 .
