### ISSUE TITLE
Channels, Favorites, Games, None Loading

### ISSUE THREAD

**Issue by Schyken** [vinszent/gnome-twitch#297]
Heyo! I installed GNOME-Twitch via the PPA on Elementary OS 0.4.1 Loki, and when opening the app, nothing populates, text or images. I've tried switching themes to eliminate that cause, and nothing changes. Screenshot: 
![image](https://user-images.githubusercontent.com/20944747/28553891-11e22c30-70ab-11e7-9919-26a587dd8564.png)

**Comment by dengelt** [comment]
In version 0.4.1 the middle tab should be names "Follows" instead of "favourites". Please check which version of gnome-twitch you have installed by running `gnome-twitch --version` and `apt show gnome-twitch`.

**Comment by Schyken** [comment]
Running this led me to an error. I got the PPA from the OMG! Ubuntu Article a while back, apparently it's unsupported now. Using the WebUpd8 PPA now. Apologies for taking your time.

**Comment by vinszent** [comment]
@Schyken Is it working now?
