### ISSUE TITLE
Chat isn't showing up when in stream

### ISSUE THREAD

**Issue by honeywave** [vinszent/gnome-twitch#299]
I'm currently on 0.4.1, installed from the webupd8 repository. I'm currently on Xubuntu 17.04 64-bit. I have tried reinstalling it, purging it, and neither fixed the issue.
![screenshot_2017-08-07_21-27-02](https://user-images.githubusercontent.com/1066456/29052296-2bd7055e-7bb7-11e7-8999-f3d68fd3621a.png)

**Comment by vinszent** [comment]
This is a bug and it's probably there, it's just it's only 1 pixel wide. If you move your cursor carefully to the right hand side of the window, you should get a double headed pointer to expand the chat.

**Comment by honeywave** [comment]
Oh. Gotcha. Thanks!
