### ISSUE TITLE
No sound

### ISSUE THREAD

**Issue by BrokenVentilator** [vinszent/gnome-twitch#300]
Using version r1042.c5c51d0 from Flathub, but not having any sound on any stream.

**Comment by TingPing** [comment]
For what its worth it works fine here. Do you use pulseaudio on the host?

**Comment by BrokenVentilator** [comment]
Yep. I'm on Fedora 26.

**Comment by BrokenVentilator** [comment]
Fixed: In settings, the wrong audio output was selected. But only Gnome-Twitch seems to follow this setting.
