### ISSUE TITLE
The develop branch doesn't compile. It's missing the gt_win_play_vod function

### ISSUE THREAD

**Issue by Eijebong** [vinszent/gnome-twitch#313]
```
../src/gt-channel-vod-container.c:72:5: warning: implicit declaration of function ‘gt_win_play_vod’
```

Which leads to the following linker error:

```
/home/eijebong/code/gnome-twitch/build/../src/gt-channel-vod-container.c:72: undefined reference to `gt_win_play_vod'
```

**Comment by vinszent** [comment]
Right, I kinda did a huge amount of work without committing any of it, so I'm trying to commit it in logical chunks. Sorry about the inconvenience, I'll try get the rest of it up this week.

**Comment by Eijebong** [comment]
No problem, just wanted to tell you :) (also ninja install doesn't install libgnome-twitch.so, do you want me to open another issue ?)

**Comment by vinszent** [comment]
Yeah sure, otherwise I might forget it :P

**Comment by Eijebong** [comment]
Oh, nevermind, it does, `/usr/local/lib` isn't in my `LD_LIBRARY_PATH` for some reasons...

**Comment by vinszent** [comment]
Should be fixed now. It will hopefully at least compile, but I can't guarantee any consistency in the UI.
