### ISSUE TITLE
Typo in meson_options.txt

### ISSUE THREAD

**Issue by chpii** [vinszent/gnome-twitch#316]
Meson encountered an error in file meson_options.txt, line 3, column 0:
    Invalid kwargs for option "use-deprecated-webkit": "descritpion"

https://github.com/vinszent/gnome-twitch/blob/e8b42a388209ba73c85eaa1bc4ca96f6e7d06461/meson_options.txt#L3

**Comment by vinszent** [comment]
Thanks, fixed now.
