### ISSUE TITLE
Dependency issues on OpenSUSE Tumbleweed

### ISSUE THREAD

**Issue by Isometries** [vinszent/gnome-twitch#319]
I've been trying to build Gnome-Twitch from tumbleweed and have come across a lot of problems. Most of them I've managed to fix, but there's one particular library that doesn't want to work.

The dependency is "Webkit2gtk-4.0", and no matter what I try, `meson build` keeps throwing this error at me. I've installed the package "webkit2gtk-4_0-injected-bundles" but it hasn't fixed it. Any idea why?

**Comment by TingPing** [comment]
`sudo zypper in 'pkgconfig(webkit2gtk-4.0)'` should do.
