### ISSUE TITLE
Error 71 (Protocol error) dispatching to Wayland display

### ISSUE THREAD

**Issue by semitom** [vinszent/gnome-twitch#320]
When I run gnome-twitch with `DRI_PRIME=1`, the program crashes when I try to play a stream. I get the following message in the terminal:

```
[21:53:45] Message - GNOME-Twitch : {GtPlayer:1310} Opening stream 'twitchpresents' with quality 'source'
[21:53:48] Critical - GNOME-Twitch : Failed to flush Wayland connection

Gdk-Message: Error 71 (Protocol error) dispatching to Wayland display.
```
Without `DRI_PRIME` it works fine. The problem is the same for both GStreamer-OpenGL and GStreamer-Clutter backends.

OS: archlinux

<details>
  <summary>$ lspci | grep VGA</summary>

```bash
  00:02.0 VGA compatible controller: Intel Corporation 3rd Gen Core processor Graphics Controller (rev 09)
  01:00.0 VGA compatible controller: NVIDIA Corporation GK107M [GeForce GTX 660M] (rev a1)
```

</details>

<details> 
  <summary>$DRI_PRIME=1 glxinfo | grep OpenGL</summary>

```bash
OpenGL vendor string: nouveau
OpenGL renderer string: NVE7
OpenGL core profile version string: 4.3 (Core Profile) Mesa 17.2.2
OpenGL core profile shading language version string: 4.30
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.0 Mesa 17.2.2
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.1 Mesa 17.2.2
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.10
OpenGL ES profile extensions:
```

</details>

**Comment by TingPing** [comment]
It is probably a problem to discuss with GStreamer.

**Comment by semitom** [comment]
Cannot confirm that GStreamer is the cause, the problem is the same with the MPV-OpenGL backend.

**Comment by vinszent** [comment]
Probably an issue with OpenGL and your Optimus setup. Does anything else using OpenGL crash with `DRI_PRIME=1`?

**Comment by tomgankema** [comment]
Other programs such as glxgears, firefox used to work fine with DRI_PRIME=1. However, I just tried running gnome-twitch again with DRI_PRIME=1 and it magically works. Still not sure what was causing this, but it seems to be fixed now.

**Comment by semitom** [comment]
Other programs such as glxgears, firefox used to work fine with DRI_PRIME=1. However, I just tried running gnome-twitch again with DRI_PRIME=1 and it magically works. Still not sure what was causing this, but it seems to be fixed now.
