### ISSUE TITLE
Only MPV works in Xmonad

### ISSUE THREAD

**Issue by ptkato** [vinszent/gnome-twitch#323]
I'm using Xmonad, actually, and I noticed that I can only get the stream to load if I use MPV-OpenGL as a player backend.

Tested with all gstreamer options, none worked.

**Comment by TingPing** [comment]
Sounds like you are missing some gstreamer plugins/codecs.

**Comment by ptkato** [comment]
@TingPing, I don't think so, since I installed everything from AUR. All the dependencies listed in the README.md are installed.

**Comment by TingPing** [comment]
AUR, sounds like you installed ancient gstreamer 0.10 libs, nothing to do with gnome-twitch. Just install `gst-libav`

**Comment by vinszent** [comment]
Are you getting any other errors that you can see in the terminal? Has anything changed from when it worked before? Is this related to #322?

**Comment by ptkato** [comment]
@vinszent, no errors. Well, before I was using Gnome 3, so there's that.

**Comment by TingPing** [comment]
Try running a compositor with Xmonad?

**Comment by ptkato** [comment]
It's working now. I didn't bother checking and installed some graphical softwares in the meantime, so I can't really tell what fixed it.
