### ISSUE TITLE
gnome-twitch crashes when resized to overlap another window

### ISSUE THREAD

**Issue by colinquirk** [vinszent/gnome-twitch#327]
I am using 4.14.11-1-ARCH, GNOME Shell 3.26.2, and GNOME Twitch - Version r1069.b5a7760.

I have been able to consistently crash gnome-twitch using the following steps:

1. load a stream
2. extend the size of the window so that is intersects, and then overlaps another window
3. reduce the size of the window so it is no long intersecting another window
4. repeat

Usually it will crash within a few seconds.

Here is the output:

GNOME-Twitch : {GtIrc:997} Joining with channel='[CHANNEL]'
nouveau: kernel rejected pushbuf: No such file or directory
nouveau: ch7: krec 0 pushes 2 bufs 12 relocs 0
[... core dump ...]
gnome-twitch: pushbuf.c:727: nouveau_pushbuf_data: Assertion `kref' failed.

**Comment by TingPing** [comment]
Probably a Nouveau bug? Can't repro with Intel or Nvidia.

**Comment by colinquirk** [comment]
Well, I just realized changing backend could help. Seems to be fixed using
gnome-twitch-player-backend-gstreamer-cairo-git r1069.b5a7760-1

before I was using 
gnome-twitch-player-backend-gstreamer-opengl-git r1069.b5a7760-1

Feel free to close, maybe it will help someone else at least.

**Comment by vinszent** [comment]
Closing this as a bug in the Nouveau graphics driver.
