### ISSUE TITLE
I have no options to login, change theme, change renderer, etc.

### ISSUE THREAD

**Issue by notnsane** [vinszent/gnome-twitch#333]
Using Linux Mint (Edit: Xfce) 18.3, app downloaded from the Software Manager. Total Linux noob so I have no idea how to fix this.

All I have are buttons to change Channels, Follows and Games, and icons to reload, search, minimize, maximize, and close. Right clicking does nothing useful.

**Comment by vinszent** [comment]
I'm not sure what window manager you are using, but you want to open the app menu. In GNOME it's usually located in the top bar [here](http://www.omgubuntu.co.uk/wp-content/uploads/2012/01/app-menu-1.jpg).

**Comment by TingPing** [comment]
In Cinnamon I believe it shows up as a menu button in the headerbar.

**Comment by notnsane** [comment]
I've been watching some videos and it seems the app is missing this icon on the top left: 

![ogrixge](https://user-images.githubusercontent.com/7162375/35646845-5905968e-06af-11e8-8073-2b0a868654ac.png)

Any ideas? I'm using Linux Mint Xfce, sorry for not mentioning it earlier. I updated everything I could, not sure if I have to update anything else.

**Comment by TingPing** [comment]
You can verify in `~/.config/gtk-3.0/settings.ini` that the `gtk-decoration-layout` value has `menu` in it: https://developer.gnome.org/gtk3/stable/GtkSettings.html#GtkSettings--gtk-decoration-layout

**Comment by vinszent** [comment]
Adding to what @TingPing wrote, you can add `gtk-shell-shows-app-menu=false` which should force GT to show the app menu like in your picture.

**Comment by notnsane** [comment]
After much googling and trying to find where the settings.ini file was, and how to actually get permissions to edit it, I inputted the two commands you told me and the icon still don't appear.

**Comment by notnsane** [comment]
Also, is there a way to clear the settings of this app so I can get the prompt to change renderer? I selected the first one and it lags on 1080p (it didn't lagged in Win10)

**Comment by notnsane** [comment]
I solved the issue by installing Linux Mint MATE (18.3), the icon appeared and I could change all, so no idea if that bug is just from the Xfce version.

Performance is OK, though it lags a bit in 1080p@60FPS, but 720p@60 works fine and that's all I need. I'm guessing it's the drivers and not this software - I'm using a very old notebook with an Intel CPU + integrated Intel GPU.

The most important issue is that I had no buffering issues, which I have when using twitch.tv via Firefox, since I use this notebook via Wi Fi and it's quite away from the router.

Thanks again for the help and gratz for the app, it's really well done. If I might add a simple suggestion (besides researching this bug with Xfce), maybe add a way to fully disconnect from the Twitch chat channel (and not just hide it), so it saves some bandwidth, which might be critical in more crowded streams. Cheers! I leave up to you the decision to close this issue or not.

**Comment by vinszent** [comment]
Great! Happy it worked in the end.
