### ISSUE TITLE
Unable to fetch your twitch follows

### ISSUE THREAD

**Issue by Gy0m** [vinszent/gnome-twitch#341]
hi, on Gnome-Twitch v0.4.1 i can't fetch my twitch follows and have this error message : 
Unable to fetch all followed channels with id '40536284' and oauth token '
-' because: A followed stream did not exist as a followed channel

**Comment by vinszent** [comment]
How many follows do you have? The Twitch API is very sketchy and is not consistent in what it returns.

**Comment by Gy0m** [comment]
Thanks vinszent, i made a big clean in my follows (really needed it) and now it works perfectly :)
