### ISSUE TITLE
Request for a new version

### ISSUE THREAD

**Issue by Aqa-Ib** [vinszent/gnome-twitch#359]
Hello. I am asking for a new version because bug #356 leaved the program on a unusable state on every distribution out there. Submiting a new version will make package maintainers to upgrade the program into a usable state again.

Thank you, regards.

**Comment by Aqa-Ib** [comment]
Oh, I understand. 
Then I will report a bug in my distribution to see if it is possible for the maintainer to apply the patch.

Thanks!

**Comment by TingPing** [comment]
The Flatpak has already had the backport for a bit.

I think it makes a lot of sense to just make an `0.4.2` which is `0.4.1` + this backport. You don't have to release off of HEAD.

**Comment by TingPing** [comment]
Here is a patch that applies to 0.4.1 for any other packages btw: https://raw.githubusercontent.com/flathub/com.vinszent.GnomeTwitch/master/0001-Use-new-Twitch-API-URL-over-SSL.patch

**Comment by vinszent** [comment]
Sure I can create a release branch.

**Comment by TingPing** [comment]
@vinszent Oh, please include https://github.com/vinszent/gnome-twitch/commit/6bee8bc0d1626087340138e66225d55ebe9d498e too.

**Comment by Aqa-Ib** [comment]
Fixed on debian:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=898768

**Comment by TingPing** [comment]
Forgot to include it in the appdata file.

**Comment by vinszent** [comment]
Right.... well not much I can do now. v0.4.1 isn't there either anyways, so I'll try remember to update it next time.

**Comment by TingPing** [comment]
Oh, Meson file wasn't even bumped either.
