### ISSUE TITLE
[ubuntu 18.04] Crash just after selecting any stream

### ISSUE THREAD

**Issue by xgorex** [vinszent/gnome-twitch#368]
Hi,
Observation: crash just after selected any Twitch stream from the main screen.
Setup: Xubuntu 18.04 with installed all updates, Gnome-twitch installed from Ubuntu repo:
Get:1 http://pl.archive.ubuntu.com/ubuntu bionic/universe amd64 gnome-twitch amd64 0.4.1-2 [164 kB]
Get:2 http://pl.archive.ubuntu.com/ubuntu bionic/universe amd64 gnome-twitch-player-backend-gstreamer-cairo amd64 0.4.1-2 [6 200 B]

Steps to reproduce:
1. start gnome-twitch
2. click on any available stream from the main screen.
3. gnome-twitch crashes, screen log:

> >gnome-twitch 
> [18:19:06] Message - GNOME-Twitch : {GtApp:370} Startup, running version '0.4.1'
> [18:19:06] Message - GNOME-Twitch : {GtFollowsManager:254} Follows file at '/home/gore/.local/share/gnome-twitch/followed-channels.json' doesn't exist
> [18:19:06] Message - GNOME-Twitch : {GtApp:339} Activate
> [18:19:06] Message - GNOME-Twitch : {GtPlayer:132} Loading chat settings
> [18:19:06] Message - GNOME-Twitch : {GtPlayer:999} Loaded player backend 'GStreamer Cairo player backend'
> [18:19:06] Message - GNOME-Twitch : {GtPlayerBackendGstreamerCairo:246} Init
> [18:19:06] Critical - GLib-GObject : g_object_get: assertion 'G_IS_OBJECT (object)' failed
> [18:19:06] Warning - GNOME-Twitch : cannot set NULL uri
> [18:19:06] Critical - Gtk : gtk_widget_add_events: assertion 'GTK_IS_WIDGET (widget)' failed
> [18:19:06] Critical - Gtk : gtk_widget_set_can_focus: assertion 'GTK_IS_WIDGET (widget)' failed
> [18:19:06] Critical - Gtk : gtk_container_add: assertion 'GTK_IS_WIDGET (widget)' failed
> [18:19:06] Warning - GLib-GObject : invalid (NULL) pointer instance
> [18:19:06] Critical - GLib-GObject : g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
> [18:19:06] Warning - GLib-GObject : invalid (NULL) pointer instance
> [18:19:06] Critical - GLib-GObject : g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
> [18:19:09] Message - GNOME-Twitch : {GtPlayer:1310} Opening stream 'ninja' with quality 'source'
> [18:19:09] Warning - GNOME-Twitch : {GtTwitch:336} Received unsuccessful response from url 'http://api.twitch.tv/api/channels/ninja/access_token' with code '400' and body '{"error":"Bad Request","status":400,"message":"Requests must be made over SSL"}'
> [18:19:09] Warning - GNOME-Twitch : {GtTwitch:594} Error getting stream access token for channel 'ninja' because: Received unsuccessful response from url 'http://api.twitch.tv/api/channels/ninja/access_token' with code '400' and body '{"error":"Bad Request","status":400,"message":"Requests must be made over SSL"}'
> Segmentation fault (core dumped)

**Comment by speace** [comment]
same as #356 which has been fixed.  
Either the ubuntu package needs to be updated or you need to update.

**Comment by DunkelheitVZ** [comment]
I have the same problem and the software says: up to date

**Comment by herrwusel** [comment]
It says it is up to date because it reflects the current state of the repository you are using. You can do `apt-cache policy gnome-twitch` to show what version is installed on your system. You should have v0.4.2 installed.

**Comment by dfstorm** [comment]
I used the PPA proposed in install instructions for Ubuntu and all it got is 0.4.1-2. Maybe the maintainers should update the "official repo"... Or propose an alternative beside building from sources or take one meant for an other distribution. ^^'
