### ISSUE TITLE
Crash on loading stream

### ISSUE THREAD

**Issue by Flavelius** [vinszent/gnome-twitch#391]
The player just crashes silently. Using --log-level=debug i was able to see this message:

{GtTwitch:336} Received unsuccessful response from url 'https://api.twitch.tv/api/channels/somechannel/access_token' with code '410' and body '{"error":"Gone","status":410,"message":"this API has been removed."}'

Looks like it's using an outdated api, as confirmed by another similar message returned from the api when signing in and merging favorites (something along the lines of "v3 is a lie, but v5 is alive" or something like that.

**Comment by tilda** [comment]
Confirmed, version 0.4.1

**Comment by ironhaven** [comment]
Same issue here

According to [this page](https://dev.twitch.tv/docs/product-lifecycle#product-lifecycle) the v3 API has been decommissioned since September 13. That means it was no longer supported for actual use. Twitch has finally pulled the plug on an important endpoint today it seems.

API v5 is sill live but it is deprecated so it may not be around forever. This app needs to migrate to something because currently it is useless for watching twitch streams

**Comment by tilda** [comment]
If anything, the best solution we have right now is using the Twitch website to find streams, then using chatterino for chat and mpv for viewing the stream.

**Comment by Flavelius** [comment]
Streamlink(/-twitch-gui) has the same problem (https://github.com/streamlink/streamlink/issues/2680), their temporary solution suggestion is to use the website's oauth token or client id.

**Comment by JRansomed** [comment]
Does anyone know if this is considered dead now?

**Comment by tilda** [comment]
Development on this has certainly stopped. As for the issue being solved, I highly doubt it. It seems that the API works one day but not the other.

**Comment by vinszent** [comment]
Yeah, I am no longer working on this project. Twitch has been working on the "new" Helix API for years and it still, to this date, doesn't even have half of the functionality of V5. But at the same time they say V5 is deprecated and can be turned off any day. Basically I just got too burnt out with Twitch constantly going back and forth on their APIs meaning that all the work I put into GNOME Twitch could just be rendered meaningless in an instance, depending on which way the wind blows. 

I think the Streamlink issue sums it up pretty well if you want more details. I don't think the API situation will ever get any better as I'm pretty sure this is just Twitch trying to lock down their platform.

Thanks everyone for using GNOME Twitch and supporting free and open source software!

**Comment by Quix0r** [comment]
So is there any easy-to-use replacement available? Sad to see that companies want to keep out FLOSS alternatives ...

**Comment by tilda** [comment]
@Quix0r I've been using Chatterino and streamlink (I believe they patched it to use Twitch's API key) recently. Not the integrated experience like gnome-twitch, but works well enough

**Comment by Quix0r** [comment]
Maybe someone can put up a script around both tools and pastebin it somewhere and link it here? @tilda

**Comment by Quix0r** [comment]
Okay, `streamlink` was relatively easy:

`$ streamlink --twitch-disable-ads --twitch-oauth-authenticate`

and then:

`$ streamlink --twitch-disable-ads https://www.twitch.tv/<user>`

to check for video formats and then choose one like:

`$ streamlink --twitch-disable-ads https://www.twitch.tv/<user> 1080p60`

But how about chat?

**Comment by Quix0r** [comment]
It also works with archived video links:
`$ streamlink --twitch-disable-ads https://www.twitch.tv/videos/535501081 1080p`

Very nice!

**Comment by tilda** [comment]
Chat is what Chatterino is used for.

**Comment by Quix0r** [comment]
Is there somewhere a complete tutorial? The learning curve here seem to be very steep compared to gnome-twitch's easiness was. And yes, I know Linux for almost 20 years.
