### ISSUE TITLE
Improve headerbar functionality and design

### ISSUE THREAD

**Issue by jangernert** [vinszent/gnome-twitch#72]
The thought behind this suggestion is: How often do you really change the volume by a few % instead of mute/unmute it and how often do you really resize the chat compared to hide/unhide it?
At least I do the later examples way more often than the former.
So my suggestion would be to pack the volume level slider into the cog-popover. At the same time remove the "show chat" checkbox in the popover (btw: whats the reason for the "dock chat" setting not being inside the "edit chat" subsection?). Now add two new toggle-buttons to the headerbar. One to show/hide the chat and one to mute/unmute the sound.
Any thoughts on this? :)

**Comment by Ippytraxx** [comment]
Absolutely. The layout I have now was just the one I put together in the beginning. Just like you as I use the application I start to realise which things I use more than others. It's great when I get feedback like this otherwise I just develop in a vacuum for my own needs.

Your suggestions seem solid and I pretty much what I had in mind as well. Same thing goes for the play/stop button which I actually have never used...

**Comment by Ippytraxx** [comment]
I've reworked the header bar and implemented some of the things you said. I think though I'll still keep the volume button mainly because it's just weird having a volume slider in the hamburger menu imo. Feel free to come up with more suggestions as you use GT more ;)!

**Comment by jangernert** [comment]
Nice changes!
So you want to keep the volume slider and not add a additional button to (un)mute the stream?
Again, I can't speak for anyone else, but the most frequent action concerning volume for me is just to mute and unmute again.
Also currently the gear-menu is still pretty empty, but the headerbar is already quite filled.
Just my 2ct :)

**Comment by Ippytraxx** [comment]
Hmm, same for me, I just remember the volume slider skewing the popup. I'll see if I can make it work somehow.

**Comment by jangernert** [comment]
Another idea:
left clicking the volume button mutes/unmutes the volume (and changes the icon to reflect that) and right clicking spawns the popover to fine tune volume. This would have both functionalities in the same place with the common one easily accessible.
Drawback: changing the volume is not as easily discoverable (it's not as common to right click buttons) and right clicking is not ideal for touch (don't know if you even care about touch).
What do you think about this?

**Comment by Ippytraxx** [comment]
Yeah I like this idea, will implement.

**Comment by Eijebong** [comment]
I think muting on right click is a better idea. As you said, right clicking on a button is not a common thing. I think that changing the volume should be more accessible than muting.

**Comment by jangernert** [comment]
I guess we will have to agree to disagree then :D
Remember: there is always the global volume slide in the top right of the screen. Most applications don't even provide their own volume slider anymore. If you just want everything to be not that loud -> turn down global volume. You only need a volume slider in a application if you want everything on your computer at for example 80% volume but THIS application needs to be only half as loud as the rest.
This would mean you are listening to multiple things at the same time. And I guess not many people do this often. Even if you do need this sometimes, compare this to the amount of times that you just want to mute a stream.
I think sane defaults like this are important. Like a wise man once said: The Needs of the Many Outweigh the Needs of the Few :D
Also compare this to the volume sliders of popular web-players like youtube or twitch itself. They all have small loudspeaker icons. When you click the icon the video is muted immediately. If you want to change the volume you first have to hover over the icon, a slider expands and then you have to move the slider.

**Comment by sergioad** [comment]
I agree with @jangernert, left click for (un)muting and right click for the popover is a perfect solution :smile:

**Comment by vinszent** [comment]
Hmmm, I'm not so sure about going against the GTK standard, which is to open the popover on left click.

But I've added the ability to mute with right click, so hopefully that helps while I figure what the best way to handle it is.
